### ISSUE TITLE
master prepared to go public

### ISSUE THREAD

**Issue by friendly** [friendly/statquotes#27]
I've looked over work on the `dev-tags` branch and see that all commits have been pulled into `master`. There was a suggestion to rename `master - master.old` and rename `dev-tags -> master`, but I think this is no longer necessary.

I suggest to go forward with the current `master', and prepare it for CRAN release.

**Comment by friendly** [comment]
Nearly ready, but I note that many of your new quotes have no tags and the list of tags contains some singletons. I'll work on this a bit before I submit.

**Comment by kwstat** [comment]
Since the searches work so well to match patterns and authors, I only added tags to expand the set of matches. For example, there used to be a topic "Tukey quotes", but now it works better to just search for Tukey as a source:
```
statquote(source="Tukey")
```
I tended to add tags for quotes that wouldn't match a pattern, e.g. "tag:anova".

Do you think there should be at least 1 tag for all quotes?  OK by me...it just takes someone to pick the tags.

**Comment by friendly** [comment]
FYI: I made a bar plot of tags ordered by frequency in `man/figures/tags-bar-sorted.png`

**Comment by friendly** [comment]
Also note that I've revised the script, `data-raw/convert_quotes_to_rda.R` to have a function, `readQuotes()` and to allow spaces after keywords.  More could be done with this, but probably is enough for now.
